
name: Storybook Visual Regression with Chromatic

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**' 

jobs:
  storybook_visual_regression:
    name: Storybook Visual Regression
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install Dependencies
        run: |
          cd nuxt-frontend
          npm install

      - name: Start Nuxt App in Development Mode
        run: |
          cd nuxt-frontend
          npm run dev &

      - name: Wait for Nuxt App
        run: sleep 20 

      - name: Run Chromatic
        run: |
          cd nuxt-frontend
          npx chromatic --project-token=chpt_a52ae26b2563628 --exit-zero-on-changes
